"lang" = "ru"

"link_to_latest_project" = "https://github.com/Vasiniyo/vasiniyo-chat-bot"
"welcome_message_for_new_members" = "Здравствуй, новый друг!\nТы присоединился к секретному чату самых лучших разработчиков ПО (и будущих самых лучших разработчиков ПО).\nЗдесь все работают сообща и помогают друг друга.\nИ хотя мы далеко не ангелы и не святые,\nно мы не травим и не троллим друг друга,\nбез особой на то причины(например указа мейнтейнера 😈)\nТак что оставь своих тараканов перед дверью и добро пожаловать!\n\nP.S. а вот здесь, ты можешь ознакомиться с нашим текущим проектом"

"mods" = [
    "core",

    "anime",
    "event",
    "likes",
    "play",
    "roll_title",
    "drink_or_not",

    "reply",
    "captcha",
    "long_message",
]

[event]
"default_winner_avatar" = "anon-ava.jpg"

[[event.winner_pictures]]
"background" = "wanted-template.png"
"avatar_size" = 380
"avatar_position_x" = 150
"avatar_position_y" = 320

[unique_file_id]
"терпи" = "ExneskoroSticky;AgADcG4AAiWZuUk"
"терплю" = "ExneskoroSticky;AgADw3sAAo8vuUk"
"накидывай" = "ExneskoroSticky;AgADumAAAk4okUk"
"винтовка-праздник" = "KantaiConcert;AgAD6AADdNYhCQ"
"все-летит" = "KantaiConcert;AgAD_QADdNYhCQ"

[categories]
good = ["хороший", "отличный", "лучший"]

[captcha_properties.gen]
"length" = 5
"banned_symbols" = "104aqiol"
"max_rotation" = 45
"margins_width" = 12
"margins_color" = "#0e1621"
"font_path" = "/usr/share/fonts/TTF/GoMonoNerdFontMono-Regular.ttf"

[captcha_properties.validate]
"timer" = 90
"update_freq" = 10
"attempts" = 5
"bar_length" = 20

[captcha_properties]
content_types = [
    "animation", "audio", "contact", "dice", 
    "document", "location", "photo", "text", 
    "sticker", "video", "video_note", "voice"
]

[sticker_to_sticker]
"терпи" = ["терплю"]
"терплю" = "терпи"
"накидывай" = "накидывай"
"винтовка-праздник" = "все-летит"

[text_to_text_to_target]
"кик" = "Давайте мб попросим кикнуть его? Реально минус вайб из-за него, всё общение обосрал"

[text_to_text]
"я не понимаю" = "Я заметила, что вы многие вещи не понимаете. Это не первая"
"люблю мисаку" = ["😳😳😳"]

"таненбаума давай" = [
    "Что хорошо в стандартах, так это то, что у вас всегда есть из чего выбрать. \n\n - Компьютерные сети",
    "Вероятно, такая ситуация сложилась из-за ошибки одного из программистов BIOS, который писай свой шедевр на ассемблере 8088.\n\n - Архитектура компьютера",
    "В компьютерной отрасли трудно подобрать название, которое бы не выглядело смешно 30 лет спустя.\n\n - Архитектура компьютера",
    "Демон - служебная программа в некоторых операционных системах (преимущественно основанных на UNIX), работающая в фоновом режиме без непосредственного взаимодействия с пользователем.\n\n - Современные операционные системы",
    "Голодание (зависание процесса) - ситуация, когда все программы бесконечно работают, но не могут добиться никакого прогресса.\n\n - Современные операционные системы",
    "Самые быстрые блокировки - отсутствие всяких блокировок.\n\n - Современные операционные системы",
    "Рецепт - это программа (алгоритм, выраженный в некой удобной форме записи), программист - центральный процессор, ингредиенты - входные данные, процесс - действия, состоящие из чтения рецепта, выпечки...\n\n - Современные операционные системы",
    "Авторы этой книги предсказывают, что конец цивилизации произойдет в полночь 31 декабря 9999 года, когда сразу уничтожатся все программы, написанные за 8000 лет на языке COBOL.\n\n - Архитектура компьютера",
    "В компьютерной отрасли трудно подобрать название, которое бы не выглядело смешно 30 лет спустя.\n\n - Архитектура компьютера",
    "Исторически использовали и развивали искусство криптографии представители четырех профессий: военные, дипломатический корпус, люди, ведущие дневник, и любовники.",
    "Боб не знает закрытого ключа Алисы, следовательно, получить зашифрованное этим ключом сообщение он мог только от Алисы. Сидя в тюрьме за лжесвидетельство и мошенничество, Алиса сможет заняться разработкой новых интересных алгоритмов с открытым ключом.",
    "Аудио-компакт-диски содержат звуковой сигнал, оцифрованный с частотой дискретизации 44 100 Гц, в результате чего они могут хранить звуки с частотами до 22 кГц, что воспринимается как достаточно качественный звук людьми, но считается весьма низким качеством среди собак, ценящих хорошую музыку.\n\n - Компьютерные сети",
    "Проект был назван Bluetooth («Синий зуб») в честь великого короля викингов по имени Гаральд Синий Зуб II (940—981), который объединил (читай, завоевал) Данию и Норвегию. Ну да, он тоже сделал это без помощи проводов.",
    "В Unix-системах есть команда - nice, позволяющая пользователю добровольно снизить приоритет свое процесса, чтобы угодить другим пользователям, но ею никто никогда не пользуется.",
]

"посоветуй аниме" = [
    "https://myanimelist.net/anime/6213/Toaru_Kagaku_no_Railgun",
    "https://myanimelist.net/anime/8023/Toaru_Kagaku_no_Railgun__Motto_Marutto_Railgun",
    "https://myanimelist.net/anime/9047/Toaru_Kagaku_no_Railgun__Misaka-san_wa_Ima_Chuumoku_no_Mato_desu_kara",
    "https://myanimelist.net/anime/9063/Toaru_Kagaku_no_Railgun__Entenka_no_Satsuei_Model_mo_Raku_Ja_Arimasen_wa_ne",
    "https://myanimelist.net/anime/16049/Toaru_Kagaku_no_Railgun_S",
    "https://myanimelist.net/anime/19697/Toaru_Kagaku_no_Railgun_S__Motto_Marutto_Railgun",
    "https://myanimelist.net/anime/22759/Toaru_Kagaku_no_Railgun_S__Daiji_na_Koto_wa_Zenbu_Sentou_ni_Osowatta",
    "https://myanimelist.net/anime/38481/Toaru_Kagaku_no_Railgun_T",
    "https://myanimelist.net/anime/61012/Toaru_Kagaku_no_Railgun_4th_Season",
]

[text_to_sticker]
"терпи" = ["терплю"]
"терплю" = "терпи"
"накидывай накидывай" = "накидывай"
"винтовка это праздник" = "все-летит"

[text_to_text_no_fuzzy]
"—" = "частые использования длинных тире - признак того, что текст написала нейросеть"

[long_message]
message_max_len = 512
long_message = [
    "Ой, длинновато... я такое не осиливаю :/",
    "Ну ты и расписался! Можно как-то короче?",
    "Я на втором слове потерялась...",
    "Это я должна всё прочитать? Серьёзно?",
    "Так, стоп. А где краткая версия для занятых?",
    "Прочитала начало… и уже устала...",
    "Может, просто скажешь, в чём суть?",
    "Если это шутка — то я её не дожила до конца.",
    "Ты уверен, что я сейчас готова к чтению романов?",
    "Лови сердечко, но читать не буду!",
    "А можно дубль покороче?",
    "Ты пока допишешь — я уже забуду, что спрашивала.",
    "Так... это сейчас что было? давай короче...",
    "У меня столько времени только на сериалы.",
    "Я аж пролистала и задумалась: это всё мне?",
    "Ты мне потом перескажешь, ладно?",
    "Если там что-то важное — сделай короткий спойлер",
    "Дай мне просто ключевое слово, я дорисую в голове",
    "Это что, диссертация на тему Как завалить чат?",
    "Я тут не в библиотеку записалась, честно...",
    "Слушай, а где кнопка TL;DR?",
    "Текст длиннее, чем моя мотивация жить...",
    "Если я прочитаю это до конца — поставь памятник.",
    "Ой, а можно аудиоверсию?",
    "Это не сообщение — это многосерийный эпос...",
    "Ты пишешь как Толстой...",
    "Я уже вызвала скорую — боюсь, умру от скуки...",
    "Если это любовное признание — я согласна, хватит!",
    "Мои глаза кричат SOS...",
    "Это не текст — это тренажёр для скорочтения...",
    "Ты хоть сам-то это перечитывал?",
    "Я пока это читала — забыла родной язык...",
    "Пока читала — прошла все стадии принятия...",
    "Ты в детстве энциклопедии глотал?",
    "Мои нейроны уже под белым флагом...",
    "Это не сообщение — крик души клавиатуры...",
    "Я бы ответила, но ещё не доплыла до конца...",
    "Если это тест на терпение — я провалила...",
    "Ты пишешь как будто тебе платят за символы...",
    "Это не текст — полотно абстракционизма...",
    "Я пока это прочитаю — дети успеют вырасти...",
    "Я уже вижу это во сне... в плохом сне...",
    "Пока читала — изобрела машину времени...",
    "Ты точно не нейросеть, которой скучно?",
    "Это не текст — квест на выживание...",
    "Я пока дочитаю — ИИ захватит мир...",
    "Я уже мысленно поставила на паузу...",
    "Ты выиграл в номинации Самый нудный текст этого года...",
    "Если бы сообщения были едой — это был бы сухарь...",
    "Пока читала — научилась медитировать...",
    "Ты сейчас как GPS — ведёшь окольными путями...",
    "Можно версию для инопланетян?",
    "Я пока это прочитаю — изобрету эликсир бессмертия...",
    "Ты пишешь как будто от этого зависит твоя жизнь...",
    "Если бы сообщения были музыкой — это был бы реквием...",
    "Извини, полностью твое словоблудие я даже не смогла дочитать. Прочитала полторы страницы, потом бросила. Если ты не можешь сформулировать свою мысль по конкретному вопросу кратко, то ты ее не можешь сформулировать вообще.",
    "Ты можешь кратко обрисовать зачем ты это здесь пишешь?",
    "Нифига у тебя ЧСВ шкалит. Не комментарий, в вступительная речь в суде. У тебя все ок? Может могу чем помочь?",
]


[custom-titles]
adjectives = [
    "алчный", "ароматный",
    "белый", "бешеный", "бледный", "бодрый", "босой", "бурый", "быстрый",
    "веселый", "вкусный", "влажный", "воинственный", "вялый",
    "гибкий", "гладкий", "грозный", "густой",
    "дикий", "добрый", "домашний", "дряхлый", "душный",
    "жаркий", "жгучий", "железный", "живой", "жирный", "жуткий",
    "забытый", "завистливый", "задумчивый", "звонкий", "злой", "золотой", "зоркий",
    "зрячий",
    "колючий", "красный", "крепкий", "кривой", "круглый",
    "ласковый", "ленивый", "липкий", "лихий", "ловкий",
    "медный", "мокрый", "молчаливый", "мрачный", "мудрый", "мягкий",
    "наш", "нежный", "низкий", "ныркий",
    "огненный", "опасный", "осырый",
    "плотный", "плотоядный", "прыгучий", "пушистый", "пыльный", "пьяный",
    "радужный", "резкий", "ржавый", "ровный", "рыжий", "рьяный", "седой", "серебряный",
    "скользкий", "сладкий", "слепой", "смелый", "старый", "страшный",
    "твердый", "темный", "теплый", "тихий", "толстый", "туалетный", "туманный",
    "тяжелый",
    "убойный", "уверенный", "угрюмый", "улыбчивый", "усталый", "ушастый",
    "хилый", "хитрый", "хлебный", "холодный", "хромой",
    "цветной", "целый",
    "честный", "чёрный", "чистый",
    "шумный", "шустрый",
    "щедрый",
    "яркий", "ясный"
]
nouns = [
    "аист", "ангел", "арлекин",
    "барон", "барс", "бегемот", "бизон", "бобёр", "бобр", "богомол", "ботан", "бык",
    "бычок",
    "вампир", "вареник", "вепрь", "викинг", "вор", "воробей", "ворон", "вурдалак",
    "гепард", "глашатай", "гном", "гоблин", "голем", "голубь", "граф", "грач", "грифон",
    "гусь",
    "дельфин", "динозавр", "дракон", "дракончик",
    "друид", "дух", "дятел",
    "единорог",
    "ёж", "еретик",
    "жираф", "жрец", "жук", "жук-дровосек",
    "зайчик", "зверь", "знахарь", "золотарь", "зомби",
    "инквизитор", "испуг", "истукан",
    "кабан", "каменщик", "капитан", "каракатица", "квак", "кентавр", "клоун",
    "козёл", "конь", "коршун", "кот", "краб", "крот",
    "лебедь", "лев", "лис", "лосось", "лось",
    "маг", "маляр", "мангуст", "манул", "мастер", "медведь", "монах", "морж", "мудрец",
    "муравей",
    "носорог",
    "обезьяна", "огурец", "олень", "орёл", "орк", "осёл", "осётр",
    "паладин", "пастух", "паук", "пегас", "пекарь", "пёс", "пингвин", "пират",
    "помидор", "попугай", "призрак",
    "рак", "рыбак", "рысь", "рыцарь",
    "самурай", "сапёр", "свин", "скат", "скелет", "скунс", "слон", "сокол", "сторож",
    "суслик", "сфинкс",
    "тигр", "троглодит", "тролль", "тюлень",
    "уж",
    "фазан", "феникс", "филин", "фокусник",
    "хакер", "хамелеон", "хирург", "хомяк", "хряк", "художник",
    "цербер", "циклоп",
    "человек", "чёрт",
    "шаман",
    "эльф",
    "ягуар", "ястреб", "ящер"
]

[[drink-or-not]]
emoji = ["🥂","🍾","🍻","🍺","🍷","🍸","🍹","🥃"]
answer = [
    "Ну а почему бы и да?", "Само собой!", "Однозначно, сегодня тот самый день!",
    "Давай, никто не осудит.", "Жизнь слишком коротка для раздумий!","Без вопросов!",
    "Разок можно!", "Время пришло!", "Судьба зовет!", "Жизнь — одна!", "Не думай — пей!",
    "Рискни сегодня!", "100% да!", "Точно да!", "Бухни смело!", "Хватит сомневаться!",
    "Ты заслужил!", "Пора расслабиться!", "День требует!", "Сердце хочет!", "Душа просит!",
    "За компанию!", "Ну хотя бы глоточек!", "Ты же взрослый!", "Почему нет?!",
    "Не откладывай!", "Точно да!"
]

[[drink-or-not]]
emoji = ["🥛","🧃","☕️","🍵","🧉","🫖","🥤","🧋"] 
answer = [
    "Не, сегодня не тот день.", "Лучше отложи на потом.", "Завтра спасибо скажешь",
    "Пожалеешь если не будешь.", "Сегодня без этого, ну его.", "Пусть организм отдохнёт.",
    "Лучше чайку.", "Не сегодня.", "Завязывай.", "Не стоит", "Отоспись.",
    "Завтра важный день", "Тебе нельзя", "Не смеши людей", "Ты же на диете",
    "Подумай о печени", "Совесть потом замучает.", "Выспись сначала!",
    "Не порть здоровье", "Лучше водички", "Завязывай уже", "Не-не-не!", "Ты лучше знаешь",
    "Организм устал", "Не твой день.", "Выбери жизнь.", "Не надо вечером", "С утра пожалеешь",
    "Потом спасибо скажешь.", "Лучше витаминки.", "Не искушай судьбу.", "Выбери трезвость!",
    "Не начинай", "Сделай паузу"
]
