from typing import Protocol

from vasiniyo_chat_bot.database.sqlite.entity import TitlesBagEntity
from vasiniyo_chat_bot.module.like.dto import Leaderboard


class TitlesRepository(Protocol):
    def init_title(self, chat_id: int, user_id: int, user_title: str) -> str | None: ...
    def update_attempt(self, chat_id: int, user_id: int) -> None: ...
    def find_user_title(self, chat_id: int, user_id: int) -> str | None: ...
    def get_user_titles(self, chat_id: int) -> list[TitlesBagEntity]: ...
    def get_user_titles_bag(self, chat_id: int, user_id: int) -> Leaderboard: ...
    def get_title_after_touch(self, chat_id: int, user_id: int) -> str | None: ...
    def get_rolls_remaining(self, chat_id: int, user_id: int) -> tuple[bool, int]: ...
    def set_current(
        self, chat_id: int, user_id: int, title_bag_id: int
    ) -> str | None: ...
    def rotate_title(self, chat_id: int, user_id: int, title: str) -> str: ...
    def steal_logic(
        self, chat_id: int, actor_id: int, title_id: int
    ) -> tuple[tuple[int | None, str | None], tuple[int | None, str | None]]: ...
    def exists(self, chat_id: int, user_id: int, title_bag_id: int) -> bool: ...
    def get_users_by_chat(self, chat_id: int) -> set[int]: ...
    def set_inventory(
        self, chat_id: int, user_id: int, title_bag_id: int
    ) -> str | None: ...
    def exchange_title(
        self, chat_id: int, user_id: int, title_bag_id: int
    ) -> tuple[str | None, int]: ...
