from typing import Protocol

from vasiniyo_chat_bot.module.likes.dto import Leaderboard


class TitlesRepository(Protocol):
    def init_title(self, chat_id: int, user_id: int, user_title: str) -> str | None: ...
    def update_last_changing(self, chat_id: int, user_id: int) -> None: ...
    def find_user_title(self, chat_id: int, user_id: int) -> str | None: ...
    def get_user_titles(self, chat_id: int) -> Leaderboard: ...
    def get_user_titles_bag(self, chat_id: int, user_id: int) -> Leaderboard: ...
    def get_title_after_touch(self, chat_id: int, user_id: int) -> str | None: ...
    def is_day_passed(self, chat_id: int, user_id: int) -> bool: ...
    def swap_title(
        self, chat_id: int, user_id: int, title_bag_id: int
    ) -> str | None: ...
    def rotate_title(self, chat_id: int, user_id: int, title: str): ...
    def steal_logic(
        self, chat_id, actor_id: int, target_id: int
    ) -> tuple[str | None, str | None]: ...
